# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJxeAVm3fXks68_-86cNCvjWJD6eTKt-
"""

import os

# Create base project folder
os.makedirs("AI_Content_Marketing_Optimizer", exist_ok=True)

# Subfolders
folders = [
    "AI_Content_Marketing_Optimizer/data/raw_data",
    "AI_Content_Marketing_Optimizer/data/processed_data",
    "AI_Content_Marketing_Optimizer/scripts",
    "AI_Content_Marketing_Optimizer/notebooks",
    "AI_Content_Marketing_Optimizer/logs"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project folders created successfully!")

import os
import pandas as pd
import re
import shutil # Import shutil for moving files

raw_folder = "/content/AI_Content_Marketing_Optimizer/data/raw_data"
clean_folder = "/content/AI_Content_Marketing_Optimizer/data/processed_data"

if not os.path.exists(clean_folder):
    os.makedirs(clean_folder)

# --- NEW: Move scraped CSVs from root to raw_data folder ---
scraped_files = [
    "youtube_large_dataset.csv",
    "google_news_articles.csv",
    "google_trends_5year_multikeywords.csv",
    "google_trends_by_region.csv",
    "google_trends_related_keywords.csv",
    "large_scraped_dataset.csv",
    "commoncrawl_filtered_dataset.csv",
]

for filename in scraped_files:
    source_path = os.path.join("/content/", filename)
    destination_path = os.path.join(raw_folder, filename)
    if os.path.exists(source_path) and not os.path.exists(destination_path):
        shutil.move(source_path, destination_path)
        print(f"Moved {filename} to {raw_folder}")
    elif not os.path.exists(source_path):
        print(f"Warning: Scraped file {filename} not found in /content/")
    else:
        print(f"{filename} already exists in {raw_folder} or source not found.")
# ---------------------------------------------------------

def clean_text(text):
    text = str(text)
    text = re.sub(r"http\S+|www.\S+", "", text)  # remove URLs
    text = re.sub(r"<.*?>", "", text)  # remove HTML tags
    text = re.sub(r"[^A-Za-z0-9.,!? ]+", " ", text)  # remove emojis and symbols
    text = re.sub(r"\s+", " ", text).strip()  # remove extra spaces
    return text

for file in os.listdir(raw_folder):
    if file.endswith(".csv"):
        print("Cleaning:", file)

        # Add on_bad_lines='skip' and engine='python' for more robust parsing
        df = pd.read_csv(os.path.join(raw_folder, file), on_bad_lines='skip', engine='python')

        # Remove duplicates
        df.drop_duplicates(inplace=True)

        # Explicitly cast columns to object dtype before filling NaN with empty strings
        # This addresses the FutureWarning regarding incompatible dtypes.
        for col in df.columns:
            if df[col].dtype == 'object': # Only cast object columns to avoid issues with numeric data
                df[col] = df[col].astype(str)
        df.fillna("", inplace=True)

        # Clean text column(s)
        for column in df.columns:
            df[column] = df[column].apply(clean_text)

        df.to_csv(os.path.join(clean_folder, file), index=False)
        print("Saved cleaned file to:", os.path.join(clean_folder, file))

print("All files cleaned successfully!")

import pandas as pd
import os

clean_folder = "/content/AI_Content_Marketing_Optimizer/data/processed_data"
standardized_folder = "/content/AI_Content_Marketing_Optimizer/data/standardized_data"

if not os.path.exists(standardized_folder):
    os.makedirs(standardized_folder)

for file in os.listdir(clean_folder):
    if not file.endswith(".csv"):
        continue

    df = pd.read_csv(os.path.join(clean_folder, file))

    # Handle each file differently based on its columns
    if file == "commoncrawl_filtered_dataset.csv":
        df['text'] = df['content'].astype(str)
    elif file in ["google_trends_5year_multikeywords.csv", "google_trends_by_region.csv"]:
        text_cols = [col for col in df.columns if col not in ['date', 'geoName', 'isPartial']]
        df[text_cols] = df[text_cols].fillna("")
        # Convert all values in text_cols to string type before aggregation
        df[text_cols] = df[text_cols].astype(str)
        df['text'] = df[text_cols].agg(" ".join, axis=1)
    elif file == "large_scraped_dataset.csv":
        df[['Title','Description','Content']] = df[['Title','Description','Content']].fillna("")
        df['text'] = df['Title'] + " " + df['Description'] + " " + df['Content']
    elif file == "youtube_large_dataset.csv":
        df[['title','description']] = df[['title','description']].fillna("")
        df['text'] = df['title'] + " " + df['description']
    else:
        print(f"Skipping unknown file structure: {file}")
        continue

    # Save standardized file
    df[['text']].to_csv(os.path.join(standardized_folder, file), index=False)
    print(f"Standardized {file} into 'text' column")

from transformers import AutoTokenizer
import pandas as pd
import os

standardized_folder = "/content/AI_Content_Marketing_Optimizer/data/standardized_data"
tokenized_folder = "/content/AI_Content_Marketing_Optimizer/data/tokenized_data"

if not os.path.exists(tokenized_folder):
    os.makedirs(tokenized_folder)

# Load the tokenizer (GPT-2, or any model you plan to use)
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token  # ensure padding token exists

for file in os.listdir(standardized_folder):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(standardized_folder, file))

        # Tokenize text column
        df['tokens'] = df['text'].apply(lambda x: tokenizer.encode(str(x), truncation=True, max_length=512))

        # Save tokenized CSV
        df.to_csv(os.path.join(tokenized_folder, file), index=False)
        print(f"Tokenized file saved: {os.path.join(tokenized_folder, file)}")

all_files = [os.path.join(tokenized_folder, f) for f in os.listdir(tokenized_folder) if f.endswith(".csv")]
dfs = [pd.read_csv(f) for f in all_files]
full_df = pd.concat(dfs, ignore_index=True)

# Save combined dataset
full_df.to_csv("/content/AI_Content_Marketing_Optimizer/data/full_tokenized_dataset.csv", index=False)
print("All datasets combined into full_tokenized_dataset.csv")

from sklearn.model_selection import train_test_split
import pandas as pd

# Ensure full_df is loaded if not already in memory
full_df = pd.read_csv("/content/AI_Content_Marketing_Optimizer/data/full_tokenized_dataset.csv")

# Filter out rows where 'text' column is NaN or empty string
# Convert to string and strip whitespace before checking for emptiness
full_df['text'] = full_df['text'].astype(str).str.strip()
full_df = full_df[full_df['text'] != 'nan'] # Remove actual 'nan' string from conversion
full_df = full_df[full_df['text'] != ''] # Remove truly empty strings

train_df, val_df = train_test_split(full_df, test_size=0.2, random_state=42)

train_df.to_csv("/content/AI_Content_Marketing_Optimizer/data/train_data.csv", index=False);
val_df.to_csv("/content/AI_Content_Marketing_Optimizer/data/val_data.csv", index=False);

print("Train/validation split done")

import os
os.environ["WANDB_API_KEY"] = "b32f491d392b858c671e8ccde858e61c45f40576"

import wandb
wandb.init(project="huggingface")

def parse_tokens(examples):
    return {'input_ids': [ast.literal_eval(t) for t in examples['tokens']]}

from transformers import AutoTokenizer, AutoModelForCausalLM
import os

# Define the model path
model_path = "/content/AI_Content_Marketing_Optimizer/model"

# Create the directory if it doesn't exist
os.makedirs(model_path, exist_ok=True)

# Initialize tokenizer and model from distilgpt2 (lighter and faster than GPT-2)
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
model = AutoModelForCausalLM.from_pretrained("distilgpt2")

# Save the model and tokenizer to the local path
model.save_pretrained(model_path)
tokenizer.save_pretrained(model_path)

print(f"Model and tokenizer initialized and saved to {model_path}")

from datasets import load_dataset

dataset = load_dataset("csv", data_files={
    "train": "/content/AI_Content_Marketing_Optimizer/data/train_data.csv",
    "validation": "/content/AI_Content_Marketing_Optimizer/data/val_data.csv"
})
print(dataset)

!pip install -U bitsandbytes
!pip install -U transformers accelerate peft

import bitsandbytes as bnb
print(bnb.__version__)

!pip install -U torch

# ====================================================
#   AI Content Marketing Optimizer – QLoRA Fine-Tuning
# ====================================================

from datasets import load_dataset
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    Trainer, TrainingArguments,
    DataCollatorForLanguageModeling, BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, TaskType
from transformers import pipeline
import torch
import os

# -----------------------------
# 1. MODEL & PATHS
# -----------------------------
base_model_name = "Qwen/Qwen2.5-1.5B-Instruct"
fine_tuned_model_path = "./AI_Content_Optimizer_Trained"
os.makedirs(fine_tuned_model_path, exist_ok=True)

# -----------------------------
# 2. QLoRA 4-bit QUANTIZATION
# -----------------------------
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

tokenizer = AutoTokenizer.from_pretrained(base_model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# -----------------------------
# 3. APPLY LORA
# -----------------------------
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    task_type=TaskType.CAUSAL_LM,
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# -----------------------------
# 4. LOAD DATASET
# -----------------------------
dataset = load_dataset("csv", data_files={
    "train": "/content/AI_Content_Marketing_Optimizer/data/train_data.csv",
    "validation": "/content/AI_Content_Marketing_Optimizer/data/val_data.csv",
})

print(dataset)

# -----------------------------
# 5. TOKENIZATION FIX
# -----------------------------
def tokenize_fn(examples):
    cleaned = []
    for entry in examples["text"]:
        if isinstance(entry, list):
            cleaned.append(" ".join(entry))
        else:
            cleaned.append(str(entry))
    return tokenizer(cleaned, truncation=True, max_length=256)

tokenized_dataset = dataset.map(
    tokenize_fn,
    batched=True,
    num_proc=4,
    remove_columns=["text", "tokens"]
)

collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# -----------------------------
# 6. TRAINING ARGS – OPTIMIZED
# -----------------------------
training_args = TrainingArguments(
    output_dir=fine_tuned_model_path,
    max_steps=5000,                         # reduced epoch
    per_device_train_batch_size=8,              # larger batch
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,              # faster updates
    warmup_steps=200,
    logging_steps=50,
    eval_strategy="no",                         # no evaluation during training
    save_strategy="steps",
    save_steps=2000,
    learning_rate=3e-4,
    weight_decay=0.01,
    fp16=True,
    save_total_limit=2,
    report_to="none",
)

# -----------------------------
# 7. TRAINER
# -----------------------------
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    data_collator=collator,
)

trainer.train()

# -----------------------------
# 8. SAVE MODEL
# -----------------------------
trainer.save_model(fine_tuned_model_path)
tokenizer.save_pretrained(fine_tuned_model_path)

print("🎉 Fine-tuning completed and model saved.")

# -----------------------------
# 9. QUICK INFERENCE TEST
# -----------------------------
device = 0 if torch.cuda.is_available() else -1
generator = pipeline(
    "text-generation",
    model=fine_tuned_model_path,
    tokenizer=fine_tuned_model_path,
    device=device,
)

test_prompt = "Suggest Instagram content ideas for fashion brands targeting college students."

outputs = generator(
    test_prompt,
    max_new_tokens=120,
    do_sample=True,
    temperature=0.7,
    num_return_sequences=3
)

print("\n================ TEST OUTPUTS ================\n")
for i, out in enumerate(outputs):
    print(f"💡 Variation {i+1}:\n{out['generated_text']}\n")

# This cell is no longer needed as its functions are now in model_generator.py and performance_metrics.py
# The main() function and __name__ == "__main__" block are removed to avoid automatic execution and rely on the Streamlit app.

# This cell is no longer needed as its functions are now in sentiment_analyzer.py

# This cell is no longer needed as its functions are now in performance_metrics.py
# The !pip install textstat is still needed and has been moved to performance_metrics.py as part of its dependencies.

def pick_best_version(generated_variations):
    highest_score = -1
    best = ""

    for text in generated_variations:
        _, sentiment_score = analyze_sentiment(text)
        metrics = performance_metrics(text, sentiment_score)
        if metrics["engagement_score"] > highest_score:
            highest_score = metrics["engagement_score"]
            best = text

    return best, highest_score

# Commented out IPython magic to ensure Python compatibility.
# %%writefile model_generator.py
# import torch
# from transformers import pipeline
# 
# model_path = "./AI_Content_Optimizer_Trained"
# device = 0 if torch.cuda.is_available() else -1
# 
# generator = pipeline(
#     "text-generation",
#     model=model_path,
#     tokenizer=model_path,
#     device=device,
# )
# 
# def build_prompt(platform, topic, tone="friendly", size="medium"):
#     size_map = {
#         "short": "Keep it concise, 1-2 sentences per idea.",
#         "medium": "Provide moderate detail, 3-4 sentences per idea.",
#         "long": "Provide detailed content with examples, 5-6 sentences per idea."
#     }
#     size_instruction = size_map.get(size.lower(), size_map["medium"])
# 
#     prompt = (
#         f"You are a social media content expert. "
#         f"Generate content for {platform} about '{topic}' with a {tone} tone. "
#         f"{size_instruction} "
#         f"Format the output as a numbered list without repetition."
#     )
#     return prompt
# 
# def generate_content(prompt, max_tokens=150, n_variations=3, temperature=0.7):
#     outputs = generator(
#         prompt,
#         max_new_tokens=max_tokens,
#         do_sample=True,
#         temperature=temperature,
#         num_return_sequences=n_variations,
#         no_repeat_ngram_size=3
#     )
#     return [out['generated_text'] for out in outputs]
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile sentiment_analyzer.py
# from transformers import pipeline
# 
# sentiment_model = pipeline("sentiment-analysis")
# 
# def analyze_sentiment(text):
#     result = sentiment_model(text)[0]
#     sentiment = result["label"]
#     score = round(result["score"], 3)
#     return sentiment, score
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile performance_metrics.py
# import textstat
# from sentiment_analyzer import analyze_sentiment
# 
# def performance_metrics(text, sentiment_score):
#     readability = textstat.flesch_reading_ease(text)
# 
#     engagement_score = (sentiment_score * 0.5) + (readability / 100 * 0.5)
#     engagement_score = round(engagement_score * 100, 2)
# 
#     return {
#         "readability": readability,
#         "sentiment_strength": sentiment_score,
#         "engagement_score": engagement_score
#     }
# 
# def pick_best_version(generated_variations):
#     highest_score = -1
#     best = ""
# 
#     for text in generated_variations:
#         _, sentiment_score = analyze_sentiment(text)
#         metrics = performance_metrics(text, sentiment_score)
#         if metrics["engagement_score"] > highest_score:
#             highest_score = metrics["engagement_score"]
#             best = text
# 
#     return best, highest_score
#

!zip -r AI_Content_Optimizer_Trained.zip /content/AI_Content_Optimizer_Trained

from google.colab import files
files.download("AI_Content_Optimizer_Trained.zip")

!zip -r Project_All_Files.zip /content/AI_Content_Marketing_Optimizer

webhook_url = "https://hooks.slack.com/services/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"

import requests
import json

requests.post(webhook_url, data=json.dumps({"text": "Slack webhook test done 🎉"}))

from google.colab import files
files.download("Project_All_Files.zip")

